class QuotaExceededError(Exception):
    ...

class RateLimitedError(Exception):
    ...

class BillingRequiredError(Exception):
    ...

class AuthError(Exception):
    ...

class UnsupportedLanguageError(Exception):
    ...

class UnsupportedVoiceError(Exception):
    ...

class ProviderUnavailableError(Exception):
    ...

class AudioGenerationError(Exception):
    ...

class UnknownProviderError(Exception):
    ...
